repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.11.3

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, Flake8-pyproject]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/jazzband/pip-tools
    rev: 6.13.0
    hooks:
      - id: pip-compile
        name: pip-compile production.in
        files: ^requirements/production\.(in|txt)$
        args: [requirements/production.in]

      - id: pip-compile
        name: pip-compile development.in
        files: ^requirements/(production|development)\.(in|txt)$
        args: [requirements/development.in]