[tool.black]
line-length = 88
target-version = ['py311']

[tool.flake8]
max-line-length = 88
extend-ignore = ['E203', 'E501']
extend-select = ['B950']

[tool.isort]
line_length = 88
profile = "black"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "."
